<a href="https://colab.research.google.com/github/SabrinaZ600/AI-four-dimension-project/blob/main/4C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ==========================================================
# Import Libraries
# ==========================================================

import os

import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
PROJECT_DIR = "/content/drive/MyDrive/AI_Brand_Project"

OUTPUT_DIR = os.path.join(PROJECT_DIR,"output")

In [ ]:
ranking_df = pd.read_csv(

os.path.join(
OUTPUT_DIR,
"brand_rankings.csv"
)

)

ranking_df.head()

   Prompt_ID       Brand  Mention  Rank
0          1        Sony        1   1.0
1          1        Bose        1   2.0
2          1  Sennheiser        1   3.0
3          1   SoundCore        0   NaN
4          1         JBL        0   NaN

In [ ]:
mention_rate = (

ranking_df

.groupby("Brand")

["Mention"]

.mean()

.rename("Mention_Rate")

)

In [ ]:
avg_rank = (

ranking_df

.groupby("Brand")

["Rank"]

.mean()

.rename("Average_Rank")

)

In [ ]:
# ==========================================================
# Top1 Rate
# ==========================================================

top1 = (
    ranking_df.assign(Top1=ranking_df["Rank"] == 1)
    .groupby("Brand")["Top1"]
    .mean()
    .rename("Top1_Rate")
)

top1

Brand
Bose          0.142857
Edifier       0.000000
JBL           0.000000
Nothing       0.000000
Sennheiser    0.142857
Sony          0.500000
SoundCore     0.142857
Name: Top1_Rate, dtype: float64

In [ ]:
# ==========================================================
# Top3 Rate
# ==========================================================

top3 = (
    ranking_df.assign(Top3=ranking_df["Rank"] <= 3)
    .groupby("Brand")["Top3"]
    .mean()
    .rename("Top3_Rate")
)

top3

Brand
Bose          0.785714
Edifier       0.071429
JBL           0.071429
Nothing       0.000000
Sennheiser    0.642857
Sony          0.928571
SoundCore     0.142857
Name: Top3_Rate, dtype: float64

In [ ]:
visibility = pd.concat(

[

mention_rate,

avg_rank,

top1,

top3

],

axis=1

)

visibility

            Mention_Rate  Average_Rank  Top1_Rate  Top3_Rate
Brand
Bose            1.000000      2.000000   0.142857   0.785714
Edifier         0.428571      5.200000   0.000000   0.071429
JBL             0.428571      4.200000   0.000000   0.071429
Nothing         0.428571      6.400000   0.000000   0.000000
Sennheiser      0.928571      2.700000   0.142857   0.642857
Sony            1.000000      1.538462   0.500000   0.928571
SoundCore       0.785714      4.000000   0.142857   0.142857

In [ ]:
#Section 3
visibility["Rank_Score"]=1/visibility["Average_Rank"]

In [ ]:
scaler=MinMaxScaler()

cols=[

"Mention_Rate",

"Rank_Score",

"Top1_Rate",

"Top3_Rate"

]

visibility[

[

c+"_Norm"

for c in cols

]

]=scaler.fit_transform(

visibility[cols]

)

In [ ]:
visibility["AI_Visibility"]=(

visibility[

[

"Mention_Rate_Norm",

"Rank_Score_Norm",

"Top1_Rate_Norm",

"Top3_Rate_Norm"

]

]

.mean(axis=1)

*100

)

In [ ]:
visibility=visibility.sort_values(

"AI_Visibility",

ascending=False

)

In [ ]:
visibility

,Mention_Rate,Average_Rank,Top1_Rate,Top3_Rate,Rank_Score,Mention_Rate_Norm,Rank_Score_Norm,Top1_Rate_Norm,Top3_Rate_Norm,AI_Visibility
Brand,,,,,,,,,,
Sony,1.000000,1.538462,0.500000,0.928571,0.650000,1.000,1.000000,1.000000,1.000000,100.000000
Bose,1.000000,2.000000,0.142857,0.785714,0.500000,1.000,0.696203,0.285714,0.846154,70.701767
Sennheiser,0.928571,2.700000,0.142857,0.642857,0.370370,0.875,0.433662,0.285714,0.692308,57.167087
SoundCore,0.785714,4.000000,0.142857,0.142857,0.250000,0.625,0.189873,0.285714,0.153846,31.360846
JBL,0.428571,4.200000,0.000000,0.071429,0.238095,0.000,0.165763,0.000000,0.076923,6.067140
Edifier,0.428571,5.200000,0.000000,0.071429,0.192308,0.000,0.073028,0.000000,0.076923,3.748783
Nothing,0.428571,6.400000,0.000000,0.000000,0.156250,0.000,0.000000,0.000000,0.000000,0.000000

In [ ]:
visibility.to_csv(

os.path.join(

OUTPUT_DIR,

"AI_Visibility_Score.csv"

),

index=True

)

print("Saved!")

Saved!